version: "3.8"

services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: feedback-nestjs-prisma
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
